version: '3.9'
services:
  mmdeploy:
    image: mmdeploy:0.7.0
    container_name: mmdeploy
    privileged: true
    volumes:
      - ${MMLAB_EXTENSION_PATH}/mmdeploy_extension:/root/workspace/mmdeploy_extension:rw
      - ${MMLAB_EXTENSION_PATH}/mmdetection_extension:/root/workspace/mmdetection_extension:rw
      - ${MMLAB_EXTENSION_PATH}/mmdetection3d_extension:/root/workspace/mmdetection3d_extension:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    # add environment variables to the container
    environment:
      # set environment variables for the container
      - MMLAB_EXTENSION_PATH=/root/workspace
      # for x11 display
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

    stdin_open: true
    tty: true
    ports:
      - "8080:8081"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
